replicaCount: 2

image:
  repository: gradyent/tech-interview
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080


ingress:
  enabled: true
  host: tech-interview-gradyent.cloudsslcert.com
  className: nginx

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 1


networkPolicy:
  enabled: true
  allowedNamespaces:
    ingress: "ingress-nginx"
    monitoring: "monitoring"

monitoring:
  enabled: false
  labels:
    prometheus: "kube-prometheus"

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault


nodeSelector: {}

tolerations: []

affinity:
  # Pod anti-affinity for security isolation
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - tech-interview
        topologyKey: kubernetes.io/hostname

# ArgoCD Ingress managed by this chart
argocd:
  ingress:
    enabled: true
    host: tech-interview-argo.cloudsslcert.com
    className: nginx
    servicePort: 80
