{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-network-policy
  labels:
    app: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.allowedNamespaces.ingress | default "ingress-nginx" }}
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.allowedNamespaces.monitoring | default "monitoring" }}
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - {} # Allow all egress traffic
{{- end }}
